name: CI
on: pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # todo re-add osx and windows
        include:
          - os: ubuntu-latest
            publish_task: publishToMavenLocal
#          - os: macos-latest
#            task: -x linkDebugSharedLinuxX64 buildMacosX64
#            publish_task: -x publishLinuxPublicationToMavenLocal publishToMavenLocal
#          - os: windows-latest
#            task: -x linkDebugSharedLinuxX64 buildWindowsX64
#            publish_task: -x publishLinuxPublicationToMavenLocal publishToMavenLocal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish artifacts locally
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ matrix.publish_task }} -Pgodot.kotlin.dev
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: benchmarks
          arguments: runBenchmarks -Pgodot.kotlin.dev

